<a href="https://colab.research.google.com/github/A01173639/Extraccion-de-Datos/blob/main/1_Extracci%C3%B3n_Datos_A01173639.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO .CSV

CARGA DE ARCHIVO XLSX

In [47]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Detalles.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [48]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

In [49]:
#Imprimo los primeros 5 registro del dataframe
df.head(5)

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [50]:
#Filtro por objeto 
#En este filtro se busca que solo aparezcan aquellos registros del vendedor Diego Armando de la columna NOMBRE_VENDEDOR
filtro1=df[df["NOMBRE_VENDEDOR"] == "DIEGO ARMANDO LEON DURAN"]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,F38005,2022-04-27,DIEGO ARMANDO LEON DURAN,MARCEGAGLIA MEXICO,5,TUE00261,"TUB INOX 3/8""ØX395MM CIR/ALETA 8500W230V",6300.00,694.60,694.60,31500.00,3472.99,5605.40,28027.01
580,F38141,2022-05-12,DIEGO ARMANDO LEON DURAN,DISMAPP PRODUCTOS IMPRESOS,2,BC00027,BC PLANA 132MMX280MM 2000W240V OCTAGO-TJ,2750.00,797.54,797.54,5500.00,1595.08,1952.46,3904.92
731,F38459,2022-06-24,DIEGO ARMANDO LEON DURAN,MEXICANA DE INGENIERIA Y MAQUINARIA,3,CAE00011,"CAE 9.4MMØx2""LONG ESC90°150W 220V Ext22""",375.00,0.00,122.35,1125.00,367.04,252.65,757.96
851,F38665,2022-07-26,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50
1296,F39592,2022-11-16,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50

In [52]:
filtro1.to_csv("Filtro1.csv")

In [51]:
#Filtro por filas
filtro2= df.iloc[2:19,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas 
filtro2
#En este filtro guarda solamente las filas de la 2 a la 19

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
10,F37050,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
11,F37051,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
12,F37052,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
13,F37053,2022-01-05,DIEGO ARMANDO LEON DURAN,SANDIBEEL BECERRA HURTADO,1,BO00051,BOB 8020 CAL.26 127V BAS28.5CMX27CM MICA,1485.25,0.00,86.22,1485.25,86.22,1399.03,1399.03
14,F37054,2022-01-05,DIEGO ARMANDO LEON DURAN,INDUSTRIAS NIBA,1,BC00023,BC INOX 114MMØX165MM 1500W 230V C/ALLEN,2095.25,0.00,742.05,2095.25,742.05,1353.20,1353.20
15,F37058,2022-01-05,DIEGO ARMANDO LEON DURAN,MOLINERA DE MEXICO,5,PT00070,"PT-100 1/8""ØX30MM EXT 1.5MT 3HILOS Z/ESP",192.50,51.73,149.60,481.25,397.08,42.90,84.17
16,F37059,2022-01-05,DIEGO ARMANDO LEON DURAN,SILCA CERAMICO PRODUCTOS,2,TP0011,"TERMOPAR CERAMICO T/K"" LONG 12"" CAL 8""",771.28,124.00,124.00,1542.56,248.00,647.28,1294.56
17,F37060,2022-01-05,DIEGO ARMANDO LEON DURAN,OSCAR VALDEZ GUADARRAMA,3,PJ31C1F1AA00,"TER J 3/16""ØX2"" EXT.2MT CON-1/2"" NPT",125.00,0.00,141.90,375.00,425.69,-16.90,-50.69
18,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,5,WRE-2133,BAN MICA 120mmØx50mm 850W 440V TTORNILLO,821.30,0.00,78.70,4106.50,393.48,742.60,3713.02

In [53]:
filtro2.to_csv("Filtro2.csv")

In [54]:
#Filtro por columnas
filtro3=df.iloc[ : , 1:4]       #Columnas consecutivas 
filtro3
##Filtra la misma cantidad de filas del df original pero limita a las primeras 4 columnas

      FECHA_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE
2    2022-01-05   DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS
3    2022-01-05   DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
...         ...                        ...                           ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ          SEVEN DAYS ALL SPORT
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ           REVUELTA MONTECARLO
1425 2022-12-23         AARON NUÑO CORDOVA                CPEG SOLUTIONS

[1426 rows x 3 columns]

In [55]:
filtro3.to_csv("Filtro3.csv")

In [56]:
df1= pd.read_excel('Detalles.xlsx', index_col=1)
df1
#leemos el excel y asignamos la primera columna del df a que sea el indice

,CVE_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
FECHA_DOC,,,,,,,,,,,,,
2022-01-05,F37034,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
2022-01-05,F37036,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2022-01-05,F37041,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
2022-01-05,F37042,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
2022-01-05,F37043,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,F39834,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
2022-12-23,F39834,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
2022-12-23,F39835,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
2022-12-23,F39837,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
2022-12-23,F39838,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [57]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4=df1.loc[["2022-01-05","2022-12-23"], ["PRECIO_UNITARIO"]]
filtro4
#En este filtro se buscan solo los registros de la columna indice que correspondan a las fechas indicadas,y muestra solo la columna de precio_unitario

            PRECIO_UNITARIO
FECHA_DOC
2022-01-05           434.48
2022-01-05          1264.05
2022-01-05           551.61
2022-01-05           140.00
2022-01-05           172.41
2022-01-05           237.07
2022-01-05         14000.00
2022-01-05            94.50
2022-01-05          1615.00
2022-01-05          1615.00
2022-01-05          1615.00
2022-01-05          1615.00
2022-01-05          1615.00
2022-01-05          1485.25
2022-01-05          2095.25
2022-01-05           192.50
2022-01-05           771.28
2022-01-05           125.00
2022-01-05           821.30
2022-01-05           821.30
2022-01-05           496.35
2022-12-23         12500.00
2022-12-23          1897.27
2022-12-23           510.00
2022-12-23          1888.00
2022-12-23           439.15
2022-12-23           925.82
2022-12-23          1910.50
2022-12-23          2020.42
2022-12-23          1177.07
2022-12-23           712.00
2022-12-23           718.60
2022-12-23          2182.35
2022-12-23          5909.84
2022-12-23          1406.00

In [58]:
filtro4.to_csv("Filtro4.csv")

In [59]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5
#Imprime los primeros 10 registros del df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11

In [60]:
filtro5.to_csv("Filtro5.csv")

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [61]:
#Filtro por comparacion
filtro6=df[df["CANT"] > 3]
filtro6
#Filtra en la columna "CANT" y muestra solo los valores numericos mayores a 3

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
15,F37058,2022-01-05,DIEGO ARMANDO LEON DURAN,MOLINERA DE MEXICO,5,PT00070,"PT-100 1/8""ØX30MM EXT 1.5MT 3HILOS Z/ESP",192.50,51.73,149.60,481.25,397.08,42.90,84.17
18,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,5,WRE-2133,BAN MICA 120mmØx50mm 850W 440V TTORNILLO,821.30,0.00,78.70,4106.50,393.48,742.60,3713.02
19,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,7,WRE-2774,BAN MICA Ø120MM X 50 MM 700W 440V T TOR,821.30,0.00,75.77,5749.10,530.41,745.53,5218.69
26,F37073,2022-01-07,LETICIA RAMIREZ HERNANDEZ,KARINA AGUILAR TORRES,5,TP0011,"TERMOPAR CERAMICO T/K"" LONG 12"" CAL 8""",485.00,124.00,124.00,2425.00,620.00,361.00,1805.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,F39826,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
1415,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,6,BP00006,BAN P INOX 1800x25mm 2800W 440V. CABLE,1888.00,0.00,294.50,11328.00,1767.02,1593.50,9560.98
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [62]:
filtro6.to_csv("Filtro6.csv")

**FILTROS BASICOS CON CONETORES LOGICOS**

In [63]:
#Filtro Y
filtro7=df[(df["PRECIO_UNITARIO"] > 500 ) & (df["NOMBRE_VENDEDOR"] == "LETICIA RAMIREZ HERNANDEZ")]
filtro7
#Filtra en la columna precio_unitario los valores mayores a 500, que haya hecho la vendedora Leticia (nombre_vendedor)

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
37,F37097,2022-01-11,LETICIA RAMIREZ HERNANDEZ,DESECHOS INDUSTRIALES CONIN,1,BN00232,BAN INOX 197MMØX152MM 3500W 440V T/TORNI,945.00,289.05,289.05,945.00,289.05,655.95,655.95
45,F37114,2022-01-14,LETICIA RAMIREZ HERNANDEZ,MARCOS FRANCISCO GOMEZ PONCE,1,TUS00049,"TUB INOX. 5/16""Øx1 MTS 900W, 127V. U TOR",803.00,140.29,140.29,803.00,140.29,662.71,662.71
50,F37125,2022-01-17,LETICIA RAMIREZ HERNANDEZ,MANUFACTURAS METALICAS,5,TUS00003,"TUB. INOX. 5/16 Øx615mm. 2000W 440V ""U""""",531.00,85.29,85.29,2655.00,426.47,445.71,2228.53
57,F37134,2022-01-17,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,RB00010,BOB 8020 CAL.19 1612W 127V CER-8CANALES,605.00,44.70,44.70,2420.00,178.80,560.30,2241.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1415,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,6,BP00006,BAN P INOX 1800x25mm 2800W 440V. CABLE,1888.00,0.00,294.50,11328.00,1767.02,1593.50,9560.98
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49

In [71]:
#Filtro o
filtro8=df[(df["PRECIO_UNITARIO"] > 1000 ) | (df["NOMBRE_VENDEDOR"] == "ALFREDO CANELA")]
#Filtra en la columna precio_unitario los valores mayores a 500, o en su defecto los que haya hecho el vendedor Alfredo Canela (nombre_vendedor)
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
10,F37050,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00146,"BAN INOX 9""ØX3"" ANCH 1700W 230V T/CABLE",2020.42,421.91,421.91,4040.84,843.82,1598.51,3197.02
1420,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,PT00079,PT-100 7.5MMØX95MM EXT.48CM 3H C/MACHO,1177.07,477.16,477.16,2354.14,954.32,699.91,1399.82
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [72]:
#Filtro not
filtro9=df[(df["PRECIO_UNITARIO"] > 1000 ) & ~(df["NOMBRE_VENDEDOR"] == "DIEGO ARMANDO LEON DURAN")]
#En este filtro se busca los registros mayores a mil que no sean del vendedor Diego
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
24,F37069,2022-01-07,AARON NUÑO CORDOVA,ADVANEX DE MEXICO,2,RP00150,REPARACION DE TERMOPAR,1500.00,0.36,0.36,3000.00,0.72,1499.64,2999.28
29,F37078,2022-01-07,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
31,F37086,2022-01-10,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
40,F37102,2022-01-12,ALFREDO CANELA,DEACERO,3,TUE00321,"TUB INOX 1/2""ØX1030MMX980MM 3KW480V ""L""",12720.00,0.00,1509.14,38160.00,4527.42,11210.86,33632.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00146,"BAN INOX 9""ØX3"" ANCH 1700W 230V T/CABLE",2020.42,421.91,421.91,4040.84,843.82,1598.51,3197.02
1420,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,PT00079,PT-100 7.5MMØX95MM EXT.48CM 3H C/MACHO,1177.07,477.16,477.16,2354.14,954.32,699.91,1399.82
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [73]:
#Convertir archivo filtrado a CSV
filtro7.to_csv("Filtro7.csv")
filtro8.to_csv("Filtro8.csv")
filtro9.to_csv("Filtro9.csv")

In [74]:
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("Filtro1.csv")
files.download("Filtro2.csv")
files.download("Filtro3.csv")
files.download("Filtro4.csv")
files.download("Filtro5.csv")
files.download("Filtro6.csv")
files.download("Filtro7.csv")
files.download("Filtro8.csv")
files.download("Filtro9.csv")